site_name: Rubeus Developers
theme:
  name: material
  palette:
    primary: Teal
    accent: Teal
  logo: 'assets/images/logo.svg'
  favicon: 'assets/images/icon.svg'
  font:
    text: Roboto
    code: Roboto Mono
  language: pt
  static_templates:
    - 404.html
  include_search_page: false
  search_index_only: true

# copyright: '&copy; 2020 Rubeus todos os direitos reservados'

extra_css:
  - 'assets/stylesheets/extra.min.css'

extra_javascript:
  - 'assets/javascripts/extra.min.js'

extra:
  search:
    language: 'pt'
  social:
    - icon: fontawesome/solid/globe
      link: 'https://rubeus.com.br/'
    - icon: fontawesome/brands/instagram
      link: 'https://www.instagram.com/canalrubeus/'
    - icon: fontawesome/brands/facebook
      link: 'https://www.facebook.com/CanalRubeus/'
    - icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/company/rubeus/'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/CanalRubeus'
    - icon: fontawesome/brands/github
      link: 'https://github.com/rubeus-tecnologia-e-inovacao'

nav:
  - API CRM:
    - Apresentação: api_crm/apresentacao.md
    - Contato: api_crm/contato.md
    - Evento: api_crm/evento.md
    - Campos personalizados: api_crm/campopersonalizados.md
    - Processo seletivo: api_crm/processoseletivo.md
    - Curso: api_crm/curso.md
    - Locais de oferta: api_crm/locaisdeoferta.md
    - Registro de processo: api_crm/registrodeprocesso.md
    - Unidade: api_crm/unidade.md
    - Métodos de listagem: api_crm/metodosdelistagem.md
    - Níveis de ensino: api_crm/niveisensino.md
    - Modalidade: api_crm/modalidades.md
    # - Usuários: api_crm/usuarios.md
  - Webhook: webhook.md
  - Endpoint: endpoint.md
  - Monitoramento de páginas:
    - Apresentação: monitoramento/apresentacao.md
    - Instalação: monitoramento/instalacao.md
    - Enviando eventos: monitoramento/enviando-eventos.md
    - Enviando dados de contato: monitoramento/enviando-data.md
    - Boas práticas: monitoramento/boas-praticas.md
    - Exemplos de códigos: monitoramento/exemplos-codigos.md
    - Integração via API: monitoramento/integracao-api.md
    - Utilizando o modo manual: monitoramento/modo-manual.md
    # - Recuperando informações: monitoramento/recuperando-informacoes.md
    # - Tracking multidomínio: monitoramento/tracking-multidominio.md
  - Tabelas auxiliares: tabelasauxiliares.md
  - Gerador de URL's: urlbuilder.md
  # - Testar API's: methodstest.md

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite